# Generated by Django 3.1.3 on 2022-02-17 20:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0121_auto_20220127_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('traceback_message', models.CharField(blank=True, max_length=500, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderOrderError', to='shopee.order')),
                ('order_line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderLineItemOrderError', to='shopee.orderlineitem')),
                ('user_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userShopOrderError', to='shopee.usershop')),
                ('user_shopee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userShopeeOrderError', to='shopee.usershopee')),
            ],
        ),
    ]
